language: objective-c
osx_image: xcode11
xcode_workspace: iOS-SDK.xcworkspace
xcode_scheme: iOS-SDK
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
before_install:
- |
  brew update
  gem install xcpretty -N --no-ri --no-doc
  gem update fastlane
install: pod install
script:
- |
  set -o pipefail
  xcodebuild clean test -workspace Feestdagen en Vakanties.xcworkspace -scheme talk7 -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty
after_success:
- ./scripts/travis/testflight.sh
